### ISSUE TITLE
Duplicated step (3/4) in help tour

### ISSUE THREAD

**Issue by amacado** [eclipse-streamsheets/streamsheets#84]
### Description

Duplicated step (3/4) in streamsheets help tour

### Steps to Reproduce

1. `Start tour` in top menu on a sheet
![image](https://user-images.githubusercontent.com/8781699/151576132-be44acd4-e00f-47a8-833b-86b98d8595f0.png)
2. Click forward to steps 3/4
3. You'll see that step 3/4 have the same content

**Expected behavior:**

Either have individual content or one step is too much.

**Actual behavior:**

![2022-01-28 streamsheets tutorial steps](https://user-images.githubusercontent.com/8781699/151575767-6915b0ed-db19-4ace-b38f-4de9af33ef55.gif)

**Reproduces how often:**

100% of the time

### Versions

Streamsheets Version 2.5.0 (Build Number 5300)
![image](https://user-images.githubusercontent.com/8781699/151576448-22a7c5ab-b2d9-4ab5-897e-11174255e4ca.png)

**Comment by cleancoderocker** [comment]
Fixed with version `2.5.2-milestone`.
