### ISSUE TITLE
Support for MQTT over TLS

### ISSUE THREAD

**Issue by TonniNTF** [eclipse-streamsheets/streamsheets#85]
## Summary

It would be really great for our possible usecases to have support for mqtt over tls. 

## Motivation

Currently using a mosquitto mqtt broker set to mqtt 5.0 but for security reason we have to run TLS. This disables to possibility to use streamsheets as a consumer/producer wit the mosquitto mqtt broker.

## Additional:

In general data security has a bigger and bigger focus, and as such encryption of data in all instances will be required everywhere.

**Comment by anreinha** [comment]
MQTT over TLS is supported. 
You can specify the desired protocol as part of the URL in the MQTT Connector. In your case this would mean that you want to use `mqtts` instead of `mqtt`, e..g. `mqtts://test.mosquitto.org:8883`.

**Comment by TonniNTF** [comment]
Thanks for the quick answer, would be nice to see it documented somewhere then. :) 
Closing since feature is already implemented
